using Dreamine.Database.Abstractions;
using Dreamine.Database.Core.Mapping;
using Dreamine.Database.Core.Providers;
using Oracle.ManagedDataAccess.Client;
using System.Data;

namespace Dreamine.Database.Oracle;

/// <summary>
/// Provides an Oracle database provider implementation.
/// </summary>
public sealed class OracleDatabaseProvider : DatabaseProviderBase
{
    /// <summary>
    /// Initializes a new instance of the <see cref="OracleDatabaseProvider"/> class.
    /// </summary>
    /// <param name="connectionString">The Oracle connection string.</param>
    public OracleDatabaseProvider(string connectionString)
        : base(connectionString)
    {
    }

    public override DatabaseProviderKind Kind => DatabaseProviderKind.Oracle;

    protected override string ParameterPrefix => ":";

    public override bool IsTableExists(string tableName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tableName);

        const string sql = """
            SELECT COUNT(1)
            FROM user_tables
            WHERE table_name = UPPER(:TableName)
            """;

        return ExecuteScalar<decimal>(sql, new { TableName = tableName }) > 0;
    }

    public override async Task<bool> IsTableExistsAsync(
        string tableName,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tableName);

        const string sql = """
            SELECT COUNT(1)
            FROM user_tables
            WHERE table_name = UPPER(:TableName)
            """;

        var count = await ExecuteScalarAsync<decimal>(sql, new { TableName = tableName }, cancellationToken)
            .ConfigureAwait(false);
        return count > 0;
    }

    protected override IDbConnection CreateConnection()
    {
        return new OracleConnection(ConnectionString);
    }

    protected override string QuoteIdentifier(string identifier)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identifier);
        return "\"" + identifier.Replace("\"", "\"\"", StringComparison.Ordinal).ToUpperInvariant() + "\"";
    }

    protected override string BuildCreateTableSql(DatabaseEntityMap map)
    {
        var columns = map.Properties.Select(property =>
        {
            var sql = $"{QuoteIdentifier(property.ColumnName)} {GetSqlType(property)}";
            if (property.IsKey)
            {
                sql += property.IsGenerated ? " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : " PRIMARY KEY";
            }

            return sql;
        });

        return $"CREATE TABLE {QuoteIdentifier(map.TableName)} ({string.Join(", ", columns)})";
    }

    protected override string GetSqlType(DatabasePropertyMap property)
    {
        var type = property.PropertyType;

        if (type == typeof(bool) ||
            type == typeof(byte) ||
            type == typeof(short) ||
            type == typeof(int) ||
            type == typeof(long))
        {
            return "NUMBER";
        }

        if (type == typeof(float) ||
            type == typeof(double) ||
            type == typeof(decimal))
        {
            return "NUMBER(18, 4)";
        }

        if (type == typeof(DateTime) || type == typeof(DateTimeOffset))
        {
            return "TIMESTAMP";
        }

        if (type == typeof(byte[]))
        {
            return "BLOB";
        }

        return "NVARCHAR2(2000)";
    }
}
