using System.Data;
using System.Reflection;
using Dreamine.Database.Abstractions;
using Dreamine.Database.Abstractions.Mapping;
using Dreamine.Database.Core.Mapping;
using Oracle.ManagedDataAccess.Client;
using Xunit;

namespace Dreamine.Database.Oracle.Tests;

public sealed class OracleDatabaseProviderTests
{
    private const string ConnectionString =
        "User Id=tester;Password=test;Data Source=localhost:1521/XEPDB1;";

    [Fact]
    public void Constructor_RejectsMissingConnectionStrings()
    {
        Assert.Throws<ArgumentNullException>(() => new OracleDatabaseProvider(null!));
        Assert.Throws<ArgumentException>(() => new OracleDatabaseProvider(""));
        Assert.Throws<ArgumentException>(() => new OracleDatabaseProvider(" "));
    }

    [Fact]
    public void Provider_ReportsKindAndPreservesConnectionString()
    {
        var provider = CreateProvider();

        Assert.Equal(DatabaseProviderKind.Oracle, provider.Kind);
        Assert.Equal(ConnectionString, provider.ConnectionString);
    }

    [Theory]
    [InlineData("orders", "\"ORDERS\"")]
    [InlineData("order\"items", "\"ORDER\"\"ITEMS\"")]
    [InlineData("한글 테이블", "\"한글 테이블\"")]
    public void QuoteIdentifier_UsesUppercaseOracleQuotes(string identifier, string expected)
    {
        Assert.Equal(expected, Invoke<string>("QuoteIdentifier", identifier));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData(" ")]
    public void QuoteIdentifier_RejectsMissingIdentifiers(string? identifier)
    {
        var exception = Assert.Throws<TargetInvocationException>(
            () => Invoke<string>("QuoteIdentifier", identifier!));

        Assert.IsType<ArgumentException>(exception.InnerException, exactMatch: false);
    }

    [Fact]
    public void CreateConnection_ReturnsClosedOracleConnection()
    {
        using var connection = Invoke<IDbConnection>("CreateConnection");
        var oracleConnection = Assert.IsType<OracleConnection>(connection);

        Assert.Equal(ConnectionState.Closed, oracleConnection.State);
        Assert.Equal(ConnectionString, oracleConnection.ConnectionString);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData(" ")]
    public void IsTableExists_RejectsMissingNames(string? tableName)
    {
        var provider = CreateProvider();

        Assert.ThrowsAny<ArgumentException>(() => provider.IsTableExists(tableName!));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData(" ")]
    public async Task IsTableExistsAsync_RejectsMissingNames(string? tableName)
    {
        var provider = CreateProvider();

        await Assert.ThrowsAnyAsync<ArgumentException>(
            () => provider.IsTableExistsAsync(tableName!));
    }

    [Fact]
    public void BuildCreateTableSql_UsesOracleTypesAndGeneratedKeySyntax()
    {
        var map = DatabaseEntityMap.Create<AllTypesEntity>();

        var sql = Invoke<string>("BuildCreateTableSql", map);

        Assert.StartsWith("CREATE TABLE \"ALL_TYPES\" (", sql, StringComparison.Ordinal);
        Assert.Contains(
            "\"ID\" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            sql,
            StringComparison.Ordinal);
        Assert.Contains("\"ENABLED\" NUMBER", sql, StringComparison.Ordinal);
        Assert.Contains("\"AMOUNT\" NUMBER(18, 4)", sql, StringComparison.Ordinal);
        Assert.Contains("\"CREATEDAT\" TIMESTAMP", sql, StringComparison.Ordinal);
        Assert.Contains("\"PAYLOAD\" BLOB", sql, StringComparison.Ordinal);
        Assert.Contains("\"NAME\" NVARCHAR2(2000)", sql, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData(nameof(AllTypesEntity.Enabled), "NUMBER")]
    [InlineData(nameof(AllTypesEntity.SmallByte), "NUMBER")]
    [InlineData(nameof(AllTypesEntity.Small), "NUMBER")]
    [InlineData(nameof(AllTypesEntity.Count), "NUMBER")]
    [InlineData(nameof(AllTypesEntity.Id), "NUMBER")]
    [InlineData(nameof(AllTypesEntity.RatioFloat), "NUMBER(18, 4)")]
    [InlineData(nameof(AllTypesEntity.Ratio), "NUMBER(18, 4)")]
    [InlineData(nameof(AllTypesEntity.Amount), "NUMBER(18, 4)")]
    [InlineData(nameof(AllTypesEntity.CreatedAt), "TIMESTAMP")]
    [InlineData(nameof(AllTypesEntity.ChangedAt), "TIMESTAMP")]
    [InlineData(nameof(AllTypesEntity.Payload), "BLOB")]
    [InlineData(nameof(AllTypesEntity.Name), "NVARCHAR2(2000)")]
    public void GetSqlType_MapsClrTypes(string propertyName, string expected)
    {
        var property = typeof(AllTypesEntity).GetProperty(propertyName)!;
        var map = DatabasePropertyMap.Create(property);

        Assert.Equal(expected, Invoke<string>("GetSqlType", map));
    }

    private static OracleDatabaseProvider CreateProvider() =>
        new(ConnectionString);

    private static T Invoke<T>(string methodName, params object[] arguments)
    {
        var method = typeof(OracleDatabaseProvider).GetMethod(
            methodName,
            BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(method);
        return (T)method.Invoke(CreateProvider(), arguments)!;
    }

    [DatabaseTable("all_types")]
    private sealed class AllTypesEntity
    {
        [DatabaseKey]
        [DatabaseGenerated]
        public long Id { get; set; }

        public bool Enabled { get; set; }

        public byte SmallByte { get; set; }

        public short Small { get; set; }

        public int Count { get; set; }

        public float RatioFloat { get; set; }

        public double Ratio { get; set; }

        public decimal Amount { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTimeOffset ChangedAt { get; set; }

        public byte[] Payload { get; set; } = [];

        public string Name { get; set; } = "";
    }
}
